name: calculadora_dizimo_oferta
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#00315D"
  image: "assets/app/splash.png"
  android: true
  ios: true

flutter_launcher_icons:
  image_path: "assets/app/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptative_icon_background: "FFFFFF"
  adaptative_icon_foreground: "assets/app/icon-android.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
